core/urls.py
from django.urls import path

from .views import IndexView, SearchView


app_name = 'core'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('search/', SearchView.as_view(), name="search"),
]

report/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
import datetime
from django.db import models


class Base(models.Model):
    created = models.DateField('Criação',auto_now_add=True)
    modified = models.DateField('Atualização',auto_now=True)
    active = models.BooleanField('Ativo',default=True)

    class Meta:
        abstract = True


class MedicalExam(Base):
    guide_number = models.AutoField(primary_key=True,editable=False)
    doctor_identifier = models.PositiveIntegerField('Código do Médico')
    doctor_name = models.CharField('Nome do Médico',max_length=100)
    query_date =  models.DateField("Date", default=datetime.date.today)
    query_value = models.DecimalField(
        "Valor da Consulta",
        max_digits=8,
        decimal_places=2,
    )
    total_value = models.DecimalField(
        "Total da Consulta",
        max_digits=8,
        decimal_places=2,
        null=True,
    )

    class Meta:
        verbose_name = 'Consulta Médica'
        verbose_name_plural = 'Consultas Médicas'
        ordering = ['-total_value']
        

    def save(self, *args, **kwargs):
        self.doctor_name = self.doctor_name.upper()
        return super(MedicalExam, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.guide_number}"


class Examination(Base):
    guide_number = models.ForeignKey(
        'core.MedicalExam',
        verbose_name="Número da Guia",
        on_delete=models.PROTECT
    )
    exam_name = models.CharField("Nome do Exame", max_length=100)
    exam_times = models.PositiveIntegerField("Número de Exames", null=True)

    class Meta:
        verbose_name = 'Exame'
        verbose_name_plural = 'Exames'
        ordering = ['-guide_number__total_value']

    def save(self, *args, **kwargs):
        self.exam_name = self.exam_name.upper()
        self.guide_number.total_value = self.guide_number.query_value * int(
                                                    self.exam_times)
        self.guide_number.save()
        return super(Examination, self).save(*args, **kwargs)

    # @property
    # def get_total_value_exam(self):
    #     return self.guide_number.query_value * int(self.exam_times)

    def __str__(self):
        return self.exam_name

core/views.py
import json
from datetime import datetime
from django.core.paginator import Paginator
from django.core import serializers
from django.db.models import Q, F
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView

from .models import MedicalExam, Examination


class IndexView(ListView):

    model = Examination
    paginate_by = 10
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['examination'] = Examination.objects.all()
        context['medical_exam'] = MedicalExam.objects.all()
        return context


class SearchView(IndexView):
    '''
    https://docs.djangoproject.com/en/3.0/topics/db/queries/#complex-lookups-with-q-objects
    '''

    def get_queryset(self, *args, **kwargs):

        term = self.request.GET.get('term', None)
        doctor_identifier = self.request.GET.get('doctor_identifier', None)

        try:
            
            qs = super().get_queryset(*args, **kwargs)

            filtros = None

            if term:
                term = term.replace('/', '-')
                term_formated = datetime.strptime(term, '%d-%m-%Y').strftime(
                                                    '%Y-%m-%d')

                filtros = Q(guide_number__query_date=term_formated)
                
                                                    
            if doctor_identifier:
                filtros = Q(guide_number__doctor_identifier=doctor_identifier)
            
            if term and doctor_identifier:
                filtros = Q(guide_number__query_date=term_formated) & Q(
                    guide_number__doctor_identifier=doctor_identifier)

            qs = qs.filter(filtros)

        except Exception as e:
            print(f'Campo de pesquisa está vazio, erro : {e}')
            qs = super().get_queryset(*args, **kwargs)

        return qs

core/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Tabela {% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-md-12">
        <h3>Tabela de Exames</h3>   
        <hr>
    </div> <!-- ./col-md-12 -->

    <div class="col-md-5 mb-2">
    <form id="search_form" method="GET" action="{% url 'core:search' %}">
    <select id="doctor_identifier" class="form-control" name="doctor_identifier">
    <option  disabled selected>Filtrar pelo nome do médico.</option>
    {% for obj in medical_exam %}
    <option  name="doctor_identifier" id="doctor" value="{{ obj.doctor_identifier }}" >{{ obj.doctor_name }} </option>
    {% endfor %}
    </select>
    </div> <!-- ./col-md-5 -->
    
    <div class="col-md-5 mb-2">
    <input type="text" name="term" id="query_date" value="{{ request.GET.term }}"
    class="form-control" placeholder="Digite a data do Exame. (Ex: 31/01/2020)">
    </div> <!-- ./col-md-5 -->

    <div class="col-md-2">
        <button type="submit" class="btn btn-success w-100">Pesquisar</button>
      </form>
    </div>

    <div class="col-md-12">
    <table class="table table-striped table border rounded bg-light shadow">
        <thead id="custom-thead">
          <tr>
              <th>Nome do Médico</th>
              <th>Número da Guia</th>
              <th>Data da Consulta</th>
              <th>Valor da Consulta</th>
              <th>Gasto por Consulta</th>
              <th>Qtde Exames</th>
          </tr>
        </thead>
        <tbody id="custom-tbody">
          {% for object in object_list %}
          <tr id="custom-tr">
            <td id="doctor_name">{{ object.guide_number.doctor_name }}</td>
              <td id="guide_number">{{ object.guide_number }}</th>
              <td id="query_date">{{ object.guide_number.query_date|date:"d/m/Y" }}</td>
              <td id="query_value">{{ object.guide_number.query_value }}</td>
              <td id="total_value">{{ object.guide_number.total_value }}</td>
              <td id="exam_times">{{ object.exam_times }}</td>
            {% endfor %}
          </tr>


        </tbody>
      </table>
      <tfoot>
        <span id="custom-tfoot">
        {% include 'parciais/_pagination.html' %}
        </span>  
      </tfoot>
    </div> <!-- ./col-md-12 -->

<div>  <!-- ./row -->
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% include 'parciais/_head.html' %}
    <title>Relatório Médico | {% block titulo %}{% endblock %}</title>
</head>
<body>
      
{% include 'parciais/_nav.html' %}

<main role="main" id="principal" class="container border rounded p-5 bg-light shadow mb-5">
{% block conteudo %} {% endblock %}
</main>

{% include 'parciais/_footer.html' %}
{% include 'parciais/_scripts.html' %}

</body>
</html>

templates/parciais/_footer.html
{% load static %}

<div id="footer" class="container-fluid bg-dark p-3 fixed">
    <div class="container text-center">
        <p class="mb-0 text-white w-100">Relatório de valor por consulta  - Desenvolvido por Liniker Oliveira &#169; </p>
    </div>
</div>

templates/parciais/_head.html
{% load static %}

  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css\global.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!--[if lt IE 9]>
        <script src="{% static 'assets/html/html5shiv.js' %}"></script>
        <script src="{% static 'assets/html/respond.min.js' %}"></script>
    <![endif]-->

templates/parciais/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light mb-5" style="background-color: #6FBFBF;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#">
      <img class="rounded" src="{% static 'img/logo.png' %}" alt="logo" width="55" height="50">
    </a>
    <ul class="navbar-nav mt-1 ">
      <li class="nav-item pr-3 pl-3"">
        <a class="nav-link" href="#">
          Home
        </a>
      </li>
      <li class="nav-item pr-3 pl-3">
        <a class="nav-link" href="{% url 'core:index' %}">
          Tabela
        </a>
      </li>
      <li class="nav-item pr-3 pl-3">
        <a class="nav-link" href="#">
          Sobre
        </a>
      </li>
      <li class="nav-item pr-3 pl-3">
      </li>
    </ul>
  </div>
</nav>

templates/parciais/_pagination.html
<div class="col mt-3 mb-3">
    <div class="row">
    
    <div class="pagination" >
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">Início</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">Anterior</a>
            </li>
            {% endif %}
    
            {% for page in page_obj.paginator.page_range %}
    
            {% if page_obj.number == page %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ page }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">{{ page }}</a>
            </li>
            {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">{{ page }}</a>
            </li>
            {% endif %}
    
            {% endfor %}
    
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">Próximo</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </div>
    </div>

templates/parciais/_scripts.html
{% load static %}

<script src="{% static 'jquery/jquery-3.4.1.slim.min.js' %}"></script>
<script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'jquery/jquery.mask.min.js' %}"></script>

<script>
$("#query_date").mask("00/00/0000");
</script>


<!-- Here I was tring to do a query with Ajax -->
<!-- <script>   
$("#doctor").change(function () {
let doctor_name = $(this).val();
let url = "doctor_name/" + doctor_name + "/";

jQuery.ajax({
    url: url,
    type: 'GET',
    data: {
        doctor_name : doctor_name, 
    },

    beforeSend: function (xhr) {
    $('#custom-tbody').empty()
    $('#custom-tfoot').remove()
    },

    success: function (data) { 
    var data = JSON.parse(data)
    console.log(data)
    $('#custom-tbody').append(
                "<tr><td id='doctor_name'>" + data + "</td><td id='guide_number'>" + data + 
                "</td><td id='query_date'>" + data + "</td><td id='query_value'>" + data + 
                "</td><td id='total_value'>" + data+ "</td><td id='exam_times'>" + data+ "</td></tr>")
    }, 

    error: function (xhr) {
    },

    complete: function () {
    }

})
});
</script> -->